---
- name: Ensure required backend packages are installed
  apt:
    name:
      - nodejs
      - npm
      - build-essential
    state: present
    update_cache: yes

- name: Install pm2 globally
  npm:
    name: pm2
    global: yes

- name: Clone tomato-app repo
  git:
    repo: 'https://github.com/geeky-bhawuk-arora/iac-multi-env-azure-webinfra.git'
    dest: "{{ app_dir }}"
    version: main
    force: yes

- name: Install backend dependencies
  npm:
    path: "{{ backend_dir }}"
    production: yes

- name: Start backend with PM2
  shell: |
    pm2 stop tomato-backend || true
    pm2 start index.js --name tomato-backend --cwd {{ backend_dir }}
    pm2 save
  args:
    executable: /bin/bash
